/**
 * MemoryEvent and MemoryEventType - canonical event protocol.
 *
 * Spec reference: Section 8
 */

/**
 * All 29 event types in the LoopTrain event protocol.
 * Unified as UPPER_SNAKE_CASE per frozen implementation decision (Section 4.9).
 */
export type MemoryEventType =
  | 'LOOP_STARTED'
  | 'ACTION_COMMITTED'
  | 'AP_SPENT'
  | 'TIME_ADVANCED'
  | 'SCENE_CHANGED'
  | 'SCENE_ENTERED'
  | 'DIALOGUE_STARTED'
  | 'DIALOGUE_ENDED'
  | 'DIALOGUE_OUTCOME_RECORDED'
  | 'CLUE_UNLOCKED'
  | 'KNOWLEDGE_CONFIRMED'
  | 'BELIEF_CREATED'
  | 'BELIEF_UPDATED'
  | 'BELIEF_CONTRADICTED'
  | 'BELIEF_CONFIRMED'
  | 'RELATIONSHIP_UPDATED'
  | 'NPC_STATE_UPDATED'
  | 'GOAL_UPDATED'
  | 'ACTION_UNLOCKED'
  | 'LOOP_FAILED'
  | 'LOOP_OUTCOME_RECORDED'
  | 'GOAL_FAILED'
  | 'CARRYOVER_MEMORY_RECORDED'
  | 'FAIL_REASON_RECORDED'
  | 'TIME_RESET'
  | 'AP_RESET'
  | 'CARRYOVER_MEMORY_APPLIED'
  | 'SNAPSHOT_WRITTEN'
  | 'RESET_APPLIED';

/**
 * Full MemoryEvent, generated by the browser on append.
 *
 * The server returns MemoryEventDraft[]. The browser generates:
 *   eventId, eventSeq, prevEventId, createdAt
 *
 * createdAt MUST be an ISO-8601 UTC string.
 *
 * Spec reference: Section 8.3
 */
export interface MemoryEvent<TPayload = unknown> {
  eventId: string;
  eventSeq: number;
  type: MemoryEventType;
  runId: string;
  loopId: string;
  chapterId: string;
  episodeId: string;
  sceneId: string;
  prevEventId: string | null;
  createdAt: string;
  payload: TPayload;
}
