'use strict';
const assert = require('assert');
const engine = require('../standalone/engine');
let s = engine.normalize(engine.START_STATE);
s.known_clues.push('claim_xiaoning_heard_ticking', 'claim_zhao_needs_actionable_evidence');
s.clock = '14:00';
let r = engine.failLoop(s, 'time_out_explosion');
assert.ok(r.loop_failure_outcome.confirmed_facts.some(x => x.id === 'claim_xiaoning_heard_ticking'));
r = engine.nextLoop(r);
assert.strictEqual(r.state.loop, 2);
assert.ok(r.state.carried_memory.includes('claim_xiaoning_heard_ticking'));
assert.ok(r.state.known_clues.includes('claim_xiaoning_heard_ticking'));
console.log('OK failure -> next loop memory carry-over');
